[book]
authors = ["Tnze"]
language = "zh"
multilingual = false
src = "specs"
title = "The Tnze Programming Language"

[output.html]
git-repository-url = "https://github.com/Tnze/TnzePL"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/Tnze/TnzePL/edit/main/{path}"
